[build]
  command = "astro build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

# Optional: force https + canonical host (once domain is set)
[[redirects]]
  from = "http://science.ionialabs.com/*"
  to = "https://science.ionialabs.com/:splat"
  status = 301
  force = true
